ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER c##equivale IDENTIFIED BY equivalebd
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER c##equivale QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO c##equivale;
GRANT "CONNECT" TO c##equivale;
ALTER USER c##equivale DEFAULT ROLE "RESOURCE","CONNECT";