# Generated by Django 3.2.22 on 2024-09-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20240919_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoarbol',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
