# Generated by Django 3.2.22 on 2024-09-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_tipoarbol_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodoentrega',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
