# Generated by Django 3.2.22 on 2024-09-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_pedido_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_final',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
