# Generated by Django 3.2.22 on 2024-09-28 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_pedido_total_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.carrito'),
        ),
    ]
