# Generated by Django 3.2.22 on 2024-10-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_pedido_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoarbol',
            name='costo',
            field=models.IntegerField(),
        ),
    ]
